services:

    # Workspace Guard
    CIHub\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuardInterface: '@CIHub\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuard'
    CIHub\Bundle\SimpleRESTAdapterBundle\Guard\WorkspaceGuard: ~
