# Configuration
ci_hub_simple_rest_admin:
    resource: 'routing/configuration.yml'
    prefix: /admin/simple-rest-adapter/config
    options:
        expose: true

ci_hub_simple_rest:
    resource: "@SimpleRESTAdapterBundle/Controller"
    type: annotation
    prefix: /pimcore-datahub-webservices/simplerest
