_simple_rest.swagger:
    path: /pimcore-datahub-webservices/simplerest/swagger-config
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: ci_hub }
_simple_rest.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: ci_hub }
_simple_rest:
    resource:
        path: ../../../Controller/
        namespace: CIHub\Bundle\SimpleRESTAdapterBundle\Controller
    type: annotation