imports:
    - { resource: services/*.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    CIHub\Bundle\SimpleRESTAdapterBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    CIHub\Bundle\SimpleRESTAdapterBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('SimpleRESTAdapterBundle')"
