pimcore_admin:
  admin_csp_header:
    exclude_paths:
      - "@^/admin/pimcore-datahub-webservices/simplerest/swagger@"

nelmio_api_doc:
    documentation:
      components:
        securitySchemes:
          Bearer:
            type: http
            scheme: bearer
      openapi: 3.0.0
      security:
        - Bearer: [ ]
        info:
            title: 'Pimcore DataHub REST Adapter'
            description: 'Endpoints provided by the REST Adapter Bundle.'
            version: 2.0.0
            license:
              name: GPL 3.0
              url: https://www.gnu.org/licenses/gpl-3.0.html
    areas:
        ci_hub:
          disable_default_routes: true
          path_patterns:
            - ^/pimcore-datahub-webservices/simplerest/{config}(?!/doc$)

framework:
    messenger:
        transports:
            datahub_es_index_queue: 'doctrine://default?queue_name=datahub_es_index_queue'
        routing:
            'CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\DeleteIndexElementMessage': datahub_es_index_queue
            'CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\InitializeEndpointMessage': datahub_es_index_queue
            'CIHub\Bundle\SimpleRESTAdapterBundle\Messenger\UpdateIndexElementMessage': datahub_es_index_queue
