name: issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  issue-sync:
    permissions:
      issues: write # should be set
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_HOSTNAME }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_AUTH_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_AUTH_TOKEN }}
      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: SUPPORT
          issuetype: Bug
          summary: (${{ github.event.issue.number }}) ${{ github.event.issue.title }}
          description: ${{ github.event.issue.body }}
          fields: '{"components": [{"name": "CI-HUB"}]}'